import Head from "next/head";
import "../styles/globals.css";
import { Toaster } from "react-hot-toast";
import { AlertTriangle } from "react-feather";
import styles from "../styles/AppLayout.module.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>NumberCruncher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
        <Component {...pageProps} />
      </main>
      <Toaster
        toastOptions={{
          style: {
            textAlign: "center",
            fontSize: "0.9rem",
          },
          error: {
            icon: <AlertTriangle color="red" size="30px" />,
          },
        }}
      />
    </>
  );
}
